# Generated by Django 5.1 on 2024-10-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('pass_hash', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('matchday', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
                ('season', models.CharField(max_length=9)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('away_team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='bet.footballteam')),
                ('home_team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='bet.footballteam')),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='MatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score_prediction', models.IntegerField(null=True)),
                ('away_score_prediction', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('match_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bet.match')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bet.user')),
            ],
            options={
                'db_table': 'predictions',
                'unique_together': {('match_id', 'user_id')},
            },
        ),
    ]
