# Generated by Django 5.1 on 2024-10-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_user_match_matchprediction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matchprediction',
            table='match_predictions',
        ),
    ]
