# Generated by Django 5.1 on 2024-10-27 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_alter_matchprediction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchprediction',
            name='match_id',
            field=models.ForeignKey(db_column='match_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bet.match'),
        ),
        migrations.AlterField(
            model_name='matchprediction',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bet.user'),
        ),
    ]
